---
# tasks file for AWS

- name: Create New EC2 Machine for code build
  ec2:
    aws_access_key: "{{ ec2.aws_access_key }}"
    aws_secret_key: "{{ ec2.aws_secret_key }}"
    key_name: "{{ ec2.key_name }}"
    group: "{{ ec2.group }}"
    instance_type: "{{ ec2.instance_type}}"
    image: "{{ ec2.image }}"
    region: "{{ ec2.region }}"
    wait: yes
    wait_timeout: 500
    vpc_subnet_id: "{{ ec2.subnet }}"
    assign_public_ip: yes
    instance_tags:
      Name: Build-Server
  register: ec2

- name: Add new instances to host group
  add_host: hostname="{{item.public_ip}}" groupname=deploy
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                state=started
  with_items: "{{ ec2.instances }}"

