- hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:
    - name: Create New EC2 Machine
      ec2:
        aws_access_key: Somekey
        aws_secret_key: Encrypted key
        key_name: test1-key
        group: test1-sg
        instance_type: t2.micro
        image: ami-123456
        instance_profile_name: robot
        region: us-east-1
        wait: yes
        wait_timeout: 500
        vpc_subnet_id: subnet-1234556
        assign_public_ip: yes
        instance_tags:
          Name: WebApp-Server
      register: ec2
    - debug: var=ec2
    - local_action: copy content="{{ ec2 }}" dest="/tmp/properties/property.txt"

    - name: Wait for SSH to come up
      local_action: wait_for
                    host={{ item.public_ip }}
                    port=22
                    state=started
      with_items: "{{ ec2.instances }}"

    - name: Check for public IP
      shell: awk -F, '/public_ip/{print $8}' /tmp/properties/property.txt | awk -F ":"  '{print $NF}'  | tr -d '"' > /tmp/properties/ip.txt

  
